### ISSUE TITLE
how do you build taxonomic classification (parentID and so on)

### ISSUE THREAD

**Issue by abubelinha** [peterdesmet/vascan-data-paper#2]
Not an issue, but a question.

The paper says "data are stored in a relational database (MySQL), which powers the search, checklist builder, taxon and name pages of the VASCAN website". It also says there are 16 taxonomic ranks, and "all taxa are linked to a classification" and you used 5 different for ranks above genus (higher classification, lycophytes, monilophytes, gymnosperms, and flowering plants) plus Flora of North America for classification below genus. 

Would it be possible to see an outline of the ER schema used to manage this complex taxonomic classification?
I am willing to generate a checklist, but I wonder which would be the best way to optimize classifications management and finally fill in the required `taxonID`, `parentNameUsageID`, `acceptedNameUsageID` ... in the resulting DwCA.

I would like to find a way which permits to "easily" modify classification above a given group of taxa, in case the person in charge decides to change her/his mind and use a different bibliographic source for the classification of those taxa.

Many thanks in advance, and congratulations for this great checklist

**Comment by peterdesmet** [comment]
Hi @abubelinha, I hope I understand your question correctly, but VASCAN does not have 5 classifications in parallel. We entertained that idea, but it became too complex. The single classification (tree) is adopting 5 sources for higher classification and one (FNA) below genus. So we only have to manage one classification. VASCAN editors can add and reassign taxa to different nodes in the classification through the backend editor (allowing them to change their mind).

It has been 9 years since I worked on VASCAN 😊, so I can't provide much up to date information or an entity-relationship diagram. So I'm hereby pinging current maintainers @canadensys and @carolesinou (and previous VASCAN developer @cgendreau) if you have more questions.

**Comment by abubelinha** [comment]
> The single classification (tree) is adopting 5 sources for higher classification and one (FNA) below genus. 

Thanks a lot @peterdesmet. Yes, that's what I understood. 
I didn't meant 5 different whole trees working in parallel (so you could just change from APG4 to Linnaeus in one click). 
Although that would be awesome: if you know of any approachs to this idea that you can share, I would be very happy to know (even just they being theoretical ER diagrams published somewhere).

> VASCAN editors can add and reassign taxa to different nodes in the classification through the backend editor (allowing them to change their mind).

That's what I am asking: how complex is this in VASCAN?  

Did perhaps your taxonomic experts work on a web application which manages all internal taxon IDs and relationships ... i.e. a visual tree that lets them drag & drop taxa from node to node? (so auto-updating parentNameUsageIDs)

Or do they work on local text files manually editing verbatim fields like dwc:higherClassification , so that when this text files are updated the whole tree is reconstructed and IDs are auto-generated by processing this field?

These are just two ideas of how I would try to do it ... but it's always better to ask experts instead of trying to reinvent the wheel.
Thanks a lot in advance to all of you.

**Comment by peterdesmet** [comment]
> Did perhaps your taxonomic experts work on a web application which manages all internal taxon IDs and relationships ... i.e. a visual tree that lets them drag & drop taxa from node to node? (so auto-updating parentNameUsageIDs)

Yes indeed, all this is done via a web application which updates the database in the background. I don't remember exactly if it was drag and drop or a dropdown box where they select the new parent. Synonymy was another big thing that was handled through the web application, e.g. if an accepted taxon became a synonym, all its children and vernacular names had to be assigned to a new accepted taxon first.
